### ISSUE TITLE
reduce the size?

### ISSUE THREAD

**Issue by benoitc** [tonyg/js-nacl#11]
The current size of the produced nacl.js is > !Mb. It would be interesting to reduce its size so it can be easily used on the web. Maybe the `--compression` arg of emscripten could help here?

**Comment by tonyg** [comment]
js-nacl is now using libsodium, compiled using emscripten's emsdk v1.36. The output file, lib/nacl_factory.js, is 658569 bytes uncompressed, and 174224 bytes gzipped. Is a 171k transfer small enough to be getting on with? If not, what other possibilities exist?

While your idea of separate packages, @3nsoft, is nice, I don't have the energy for it at the moment. Perhaps you'd like to have a go? I imagine it would involve carving up the underlying libsodium.
