### ISSUE TITLE
Browser benchmarks

### ISSUE THREAD

**Issue by jxson** [tonyg/js-nacl#14]
This is not an issue really but wanted to let you know I copied over your benchmarks to http://jsperf.com/js-nacl

On a project I am working on we have seen some issues in safari using nacl.crypto_secretbox() on larger chunks of data (greater than 4mb) so I will be adding that to the tests on jsperf. If there is any other functions that should have a test let me know, I am happy to add them.

**Comment by tonyg** [comment]
Thanks very much! I'm sorry it has taken me this long to say this.
