### ISSUE TITLE
eval used in library?

### ISSUE THREAD

**Issue by getify** [tonyg/js-nacl#15]
I have a CSP on my site which does not allow `eval()`, and trying to use nacl, I get errors thrown indicating the nacl library is trying to use it. What's the reason behind that? Is there anyway around it without just basically opening up a big hole in my CSP?

**Comment by tonyg** [comment]
js-nacl is now using libsodium, compiled using emscripten's emsdk v1.36. The newer emscripten output may have changed the situation regarding `eval` - it'd be worth another look!

**Comment by tonyg** [comment]
I'm fairly sure that no references to eval remain in the code (after a quick grep of the build output), so on the strength of that assumption, I'm going to close this. Please do reopen if it turns out still to be a problem!
