### ISSUE TITLE
newbie question: password -> key

### ISSUE THREAD

**Issue by pomke** [tonyg/js-nacl#35]
I'm trying to encrypt a user's nacl private key with a passphrase using nacl.crypto_secretbox, I'm unsure how I'm supposed to turn a password/passphrase into a valid key for secretbox.

thanks!

**Comment by tonyg** [comment]
For that you want a Password-Based Key Derivation Function (PBKDF), like (in order of preference) [scrypt][], [bcrypt][], or [pbkdf2][].

[scrypt]: https://en.wikipedia.org/wiki/Scrypt
[bcrypt]: https://en.wikipedia.org/wiki/Bcrypt
[pbkdf2]: https://en.wikipedia.org/wiki/PBKDF2

You may also find <https://gist.github.com/tqbf/be58d2d39690c3b366ad> of interest.

**Comment by 3nsoft** [comment]
You need a different functions for this. Short answer: scrypt. A threat model for  is a little different, and best derivation uses most memory and amount of operations.

You have javascript implementation options:
1) js-scrypt: https://github.com/tonyg/js-scrypt
2) scrypt-async-js: https://github.com/dchest/scrypt-async-js
3) scrypt function in ecma-nacl: https://github.com/3nsoft/ecma-nacl

Option (1) is emscripten, but it has no callback to report a progress of key derivation, which you may want for a responsive GUI that still has strong (long) derivation.
Option (2) does processing in chunks with timeouts. There should be a way to signal about process between the "ticks".
Option (3) does processing uninterrupted, but with a callbacks. It is meant to be in web worker, and browser tests can be used as examples.

**Comment by pomke** [comment]
Ty @tonyg, that gist was really helpful, and thanks @3nsoft for the great breakdown, npm is often overwhelming when it comes to too-many-options, that was fantastically helpful :)
