### ISSUE TITLE
"Typed arrays 2 must be run on a little-endian system"

### ISSUE THREAD

**Issue by athanclark** [tonyg/js-nacl#39]
Hello, I'm getting a strange error with minimal code:

```js
nacl_factory.instantiate(function(nacl) {
  // literally do nothing
});
```

Which gives me this error:

![](http://i.imgur.com/xWicEpW.png)

This is on firefox 46.0.1 on linux kernel 4.4.0-22, ubuntu 16.04. Am I doing something wrong here? I'm running this on a traditional x86_64 machine, it isn't likely something unweildy. But, now that I recognize it, this is a version installed from `bower`; maybe it installed an old version somehow?

**Comment by athanclark** [comment]
It was the bower version! After switching to the version available on cdnjs, it works.

**Comment by tonyg** [comment]
Oh, yikes, ok :-( Thanks for picking up on this. Is it repeatable? Is there anything I need to do to, eg, flush some stale state from somewhere or other?

**Comment by athanclark** [comment]
I think it should be immediately repeatable, this was the result I got after clearing my cache and everything. If I'm not mistaken, bower fetches the library straight from github, so it should be this latest version. If it interests you, I could probably whip together a nice verification test suite with jsverify :)

**Comment by tonyg** [comment]
@athanclark: Improvements to the tests would be very much appreciated, absolutely!

I've just tagged v1.2.1, which seems to have updated bower, so hopefully this issue is now resolved.
