### ISSUE TITLE
new function crypto_sign_seed_keypair is not exported

### ISSUE THREAD

**Issue by jpfox** [tonyg/js-nacl#40]
Hi,

In lib/nacl_factory.js, only old deprecated function crypto_sign_keypair_from_seed is exported, so we must call this deprecated function :-(
Could you add : 

```
    exports.crypto_sign_seed_keypair = crypto_sign_seed_keypair;
    exports.crypto_box_seed_keypair = crypto_box_seed_keypair;
```
Thanks for your great job :+1:

**Comment by tonyg** [comment]
Thanks for pointing out that mistake - and you're welcome!
