### ISSUE TITLE
hey I'm getting crashes when trying to unbox larger files

### ISSUE THREAD

**Issue by mpc20001** [tonyg/js-nacl#45]
I'm using a foreach statement and iterating on an array that contains encrypted files. js-nacl crashes if the files is larger than 10kbs. Any idea why?

**Comment by tonyg** [comment]
Are you giving it enough memory? Can you supply a program I can run to see it failing?

**Comment by mpc20001** [comment]
we just ended up encrypting large files separately using sa node utility and then encrypting the key to that file using js-nacl. I can't post the code but I was running it in an electron project.
