### ISSUE TITLE
Library throws error in Google Chrome

### ISSUE THREAD

**Issue by istrau2** [tonyg/js-nacl#52]
Running this library in google chrome, the following error gets thrown:

> failed to asynchronously prepare wasm: CompileError: WebAssembly Instantiation: Wasm code generation disallowed by embedder

This seems related to our content security policy (which is strict):
https://stackoverflow.com/questions/48523118/wasm-module-compile-error-in-chrome-extension

We cannot put `'unsafe-eval'` on our `script-src` for obvious reasons. 

Any insights as to what is going wrong and how it can be fixed?

**Comment by tonyg** [comment]
That looks like something specific to Chrome extension configuration - I'm afraid I have no insight to offer for that case. I suspect that the commenter on the page you linked was right, and that enabling wasm in an extension could well be an attack vector. One downside of using wasm for this library, I suppose. Have you considered using tweetnacl or some other pure-JS implementation of Ed25519/X25519 and friends?
