### ISSUE TITLE
Key pair generation fails on IPhones

### ISSUE THREAD

**Issue by ivknv** [tonyg/js-nacl#53]
This problem was reported by all IPhone users of a certain website.
One specific user used IPhone XS Max and Safari browser. 

I don't have an IPhone, so I can't test this.

Code (approximate) used in the website
```js
function bufferToHex(buffer) {
    var s = '', h = '0123456789ABCDEF';
    (new Uint8Array(buffer)).forEach((v) => { s += h[v >> 4] + h[v & 15]; });
    return s;
}

function generateKeyPair() {
    var pass = 'some string';
    var salt = bufferToHex(nacl.random_bytes(32));
    var keyPair = null;

    try {
        keyPair = nacl.crypto_box_seed_keypair(pass + salt);
    } catch(err) {}

    if (keyPair){
        return {publicKey: keyPair.boxPk, privateKey: keyPair.boxSk};
    }

    return keyPair;
}

console.log(generateKeyPair()) // should not be null
```

`generateKeyPair()` returns `null` if it couldn't generate the key pair.

**Comment by tonyg** [comment]
Unfortunately, I don't have any kind of iPhone either.

**Comment by ivknv** [comment]
It turns out that the problem was not in the library. It was caused by passing strings instead of `Uint8Array`.
Somehow it didn't cause any noticeable errors in other browsers. Whoever wrote that code (which wasn't me :) ) should've been more careful. Sorry for the false alarm.

**Comment by tonyg** [comment]
I'm glad you found the source of the problem! Thanks for the update.
