### ISSUE TITLE
Type inconsistency with latest version

### ISSUE THREAD

**Issue by Diiaablo95** [tonyg/js-nacl#56]
I tried installing the package via NPM, but I could see that while the package is at version 1.3.2, the types are at version 1.3.0. 

I don't know if that is related or not, but the types do not expose the sealed box functions for anonymous encryption.

**Comment by tonyg** [comment]
Hi,
Thanks for the report. The types are maintained elsewhere, I'm afraid: https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/js-nacl. Perhaps you could open an issue or submit a patch there.
Cheers,
  Tony
