### ISSUE TITLE
No updates in 3 years?

### ISSUE THREAD

**Issue by CholoTook** [tonyg/js-nacl#57]
Would you still recommend to use this project, or has it been made obsolete?

(Sorry for the very dumb question, as a total outsider looking in, I really don't know!)

Many thanks,
Dan.

**Comment by tonyg** [comment]
Hi,
I'd say give it a try, yeah, no reason I know of not to use it. There are other js bindings that may be more to your taste, however: see https://doc.libsodium.org/bindings_for_other_languages
Cheers,
  Tony

**Comment by CholoTook** [comment]
Thank you!
