### ISSUE TITLE
Is this library still maintained?

### ISSUE THREAD

**Issue by samuel-lucas6** [tonyg/js-nacl#58]
Hi @tonyg, I'm currently trying to tidy up the bindings linked on the libsodium website. If this library is still maintained, then please let me know; otherwise, the link to this library will [likely](https://github.com/jedisct1/libsodium-doc/pull/156#issuecomment-1067834246) be removed from the [bindings](https://doc.libsodium.org/bindings_for_other_languages) page to help users find up to date and maintained bindings.

**Comment by tonyg** [comment]
Hi! Yep, it's still maintained. It's just... finished. As far as I'm aware, there are a lot of people using the library, even though there's little discussion of it. And the API has a different feel to that of libsodium.js, which I think makes it worth preserving as an option.

**Comment by tonyg** [comment]
(Incidentally I've just bumped the libsodium version underpinning the library to 1.0.18-stable. Thanks for the impetus to do so :) )

**Comment by samuel-lucas6** [comment]
Thanks for the reply. Nice :)
